### ISSUE TITLE
Is the best way to implement a Wayland protocol with wlc?

### ISSUE THREAD

**Issue by Timidger** [vberger/wayland-rs#102]
Sorry if this is off-topic, couldn't find a better place to ask this / reach you.

I have implemented the unstable redshift Wayland protocol in Way Cooler recently, but I found it a bit difficult to do without dropping down into the primitives exposed by `wayland_sys`. I assume part of this is due to wlc, but there were a few things I had to implement that I expected `wayland-scanner` to do for me.

For example, I expected `wayland-scanner` to make some `#[repr(C)]` structs which I could fill in with `extern "C"` functions that would trigger when the appropriate request was fired from the client. However, [I had to make those myself](https://github.com/way-cooler/way-cooler/pull/285/files#diff-3cc3b4794645f895738d977771beb171R63) which I thought a bit strange.

I don't mind working this way, at least until Way Cooler switches to a different compositor framework that will hopefully be less opinionated than wlc, but I wanted to double check I'm not doing this in a very silly way.

[The PR in question](https://github.com/way-cooler/way-cooler/pull/285/files)

**Comment by vberger** [comment]
The main reason `wayland-scanner` does not make these struct is simply because `wayland-client` & `wayland-server` do not use them. I'm instead using the dispatcher mechanism, which allows me to plug my lib at a lower level in the C libraries, to expose the handler traits I have in `wayand-client` & `wayland-server`.

As such, if you need to implement a protocol extension for working with WLC, you'll need to do it the WLC way I'm afraid. I haven't built a compability mechanism, and creating a global using wayland-server on a display chose event-loop is managed by WLC would be hazardous at least.

**Comment by Timidger** [comment]
Ah, I understand. Thanks for the info!
